### ISSUE TITLE
Button in app's admin UI to check whether /.well-known/openid-configuration exists

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/solid-nextcloud#13]
It would be nice if the server admin can test their .htaccess rule and test whether https://your-server.com/.well-known/openid-configuration redirects to https://your-server.com/apps/solid/openid.

**Comment by michielbdejong** [comment]
And then update the install instructions in the readme

**Comment by ylebre** [comment]
Since we are handling well-known inside the app now (and no longer in apache configuration), we should be confident that it is always available now.

See: [solid/lib/WellKnown/SolidHandler.php](https://github.com/pdsinterop/solid-nextcloud/blob/9fd67da93992aecc04e8ee47cfe4df69263c8e31/solid/lib/WellKnown/SolidHandler.php#L4)
