### ISSUE TITLE
500 error on profile

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/solid-nextcloud#56]
https://cloud.pondersource.org/index.php/apps/solid/@michielbdejong/ gives a 500

**Comment by Potherca** [comment]
We might want to start looking towards using `"phpunit/phpunit": "^8|^9", as we are currently also doing for  [flysystem-rdf](https://github.com/pdsinterop/flysystem-rdf/blob/main/composer.json) and [flysystem-nextcloud](https://github.com/pdsinterop/flysystem-nextcloud/blob/main/composer.json) in order to support PHP7 and PHP8

**Comment by graphixillusion** [comment]
I'm still having this error. How to fix this? Ty
