### ISSUE TITLE
App solid cannot be installed because appinfo file cannot be read.

### ISSUE THREAD

**Issue by lumenpink** [pdsinterop/solid-nextcloud#60]
I'm trying to install version 0.0.3 from the store.

Nextcloud 23 from docker hub (php 8.0.14) and mysql 8

occ status returns
  - installed: true
  - version: 23.0.0.10
  - versionstring: 23.0.0
  - edition:
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
  
  Thanks!

**Comment by Potherca** [comment]
Hello!

Currently we are having issues with support for PHP8. Due to underlying dependencies, we currently cannot support PHP8 until we've removed support for php 7.3.

The ticket to follow for this is #59.

Due to the holidays and an upcoming deadline for another project of ours (the [Solid Migrator](https://dapsi.ngi.eu/hall-of-fame/pds-migrator/)), fixes for this probably won't land until mid to late January.

**Comment by Potherca** [comment]
Update: We are currently hard at work to support NC24 and PHP8+. at this point I am not yet sure if this means we also support NC23 or not.

**Comment by Potherca** [comment]
This should be resolved with the upcoming v0.6.0 release...

**Comment by ylebre** [comment]
Version 0.8.1 is available in the store. If all is well, it should 'just install' now.
